"""Daily-state constants for Stage 3A."""

KNOWLEDGE_PRECISION_DAY = "DAY"
KNOWLEDGE_CUTOFF_BASIS = "FROZEN_APPLICABILITY_TARGET_DATE_END_OF_DAY_VIEW"
TRANSACTION_TIME_BASIS_UNAVAILABLE = "HISTORICAL_DATABASE_TRANSACTION_TIME_UNAVAILABLE"
