"""Stage 5C analysis constants."""

from __future__ import annotations

from pathlib import Path

STAGE5C_METHOD_VERSION = "stage5c_claim_expressibility_analysis_v1_frozen"
STAGE5C_SCHEMA_VERSION = "stage5c_claim_expressibility_analysis.v1"
STAGE5C_STATUS = "FROZEN"
STAGE5C_GENERATED_AT = "2026-08-11T20:00:00+08:00"
GENERATED_AT_SEMANTICS = "OFFLINE_RECONSTRUCTION_TIME"

STAGE5B_ARTIFACT = Path("artifacts/stage5b_deterministic_claim_builder_v1")
STAGE5C_OUTPUT = Path("artifacts/stage5c_claim_expressibility_analysis_v1")
STAGE5B_TAG = "stage5b-claim-builder-v1-frozen"
STAGE5B_COMMIT = "0be7a85ed6f5bcea31b82af9e1e8380037b3dd34"
STAGE5A_TAG = "stage5a-claim-contract-v1.1-frozen"
STAGE4_TAG = "stage4-metrics-v1.1-frozen"
STAGE4_SOURCE_SNAPSHOT_SHA256 = "906a6d8636483adc5e71099af1c4a801f21dff427beb6c8ac198dd435244373d"
STAGE4_SOURCE_TREE_HASH = "a8e9eee5c5e26e266fffd0a495be51dbea0727a09ac84c63ac9834d2e7602464"

CLAIM_TYPE_ORDER = [
    "OPERATIONAL_RESPONSE_ATTENTION",
    "GEOLOGICAL_EVIDENCE_ATTENTION_REVIEW",
    "COUPLED_ATTENTION_REVIEW",
    "FORWARD_GEOLOGICAL_ATTENTION",
    "OBSERVED_GEOLOGICAL_CONDITION",
    "FORECAST_GEOLOGICAL_CONDITION",
]

UNKNOWN_VALUES = {"", "UNKNOWN", "NULL", "NONE", "UNMAPPED", "UNMAPPABLE"}

REASON_GROUPS = {
    "UNKNOWN_SOURCE_VALUE": "SOURCE_VALUE_UNAVAILABLE",
    "CONTEXT_ONLY_ROLE": "CONTEXT_POLICY_BOUNDARY",
    "STATE_ROLE_NOT_ALLOWED": "CONTEXT_POLICY_BOUNDARY",
    "REQUIRED_EPISTEMIC_STATUS_MISSING": "EPISTEMIC_PROOF_INSUFFICIENT",
    "REQUIRED_METRIC_UNAVAILABLE": "METRIC_UNAVAILABLE",
}
